### PR TITLE
Added support for parsing from glite type users.conf file

### PR DESCRIPTION
**Pull request by kashif74**

### CODE REVIEW

**Comment by kreczko** [comment]
Hi Kashif,

I am wondering if it would make sense to make the filename (currently /var/cache/user.conf) into a parameter of the function. The functions are currently not used anywhere, so it is hard to tell how useful this would be.

**Comment by kashif74** [comment]
Hi Luke
I removed hard coded link to /var/cache/user.conf and made it a function. Also changed name of few function to make it more explicit and less chances of colliding with other function names. I am not sure that whether I have to make a new pull request or previous pull request will incorporate new changes.

**Comment by kreczko** [comment]
Hi Kashif,

Thanks for the changes. As for the usual git workflow, the pull request is automatically updated.
However, you might want to tidy up the history (it's a good exercise) by creating a new branch with your changes\* and doing `git rebase --interactive <commit of first change>^`.
This will then give you the option to merge commits and will result in a nicer history.

If you don't have the time for this, feel free to merge the current pull request.
- As you have already uploaded the changes, merging them locally will result in conflicts. Hence the new branch.

**Comment by kashif74** [comment]
some other time ;) 
Going to merge

**Pull request merged**
